engines:
  phpmd:
    enabled: true
    checks:
      Naming/ShortVariable:
        enabled: false
      CleanCode/StaticAccess:
        enabled: false

ratings:
  paths:
    - "src/**/*.php"

exclude_paths:
  - "tests/"
  - "vendor/"
